sudo: enabled
language: c

branches:
  only:
  - master

notifications:
  email:
    on_success: never

# Do not error on failures in OSX, which is not the target system
matrix:
  allow_failures:
    - os: osx

# Follow DynamoRIO's lead and use a jobs approach over os, compiler, env matrix
jobs:
  include:

    # Default Linux builds with gcc and clang
    - stage: default
      os: linux
      dist: xenial
      compiler: gcc
    - stage: default
      os: linux
      dist: xenial
      compiler: clang
    - stage: default
      os: linux
      dist: xenial
      compiler: gcc
      env: LDFLAGS="-static"
    - stage: default
      os: linux
      dist: xenial
      compiler: clang
      env: LDFLAGS="-static"
    
    # ARM architecture build
    - stage: arm
      os: linux
      dist: xenial
      compiler: gcc
      install:
        - sudo dpkg --add-architecture i386
        - sudo apt-get update
        - sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1
        - sudo apt-get install gcc-arm-linux-gnueabihf
      env: TARGET="--target arm-linux-gnueabi" CFLAGS="-march=armv7" CC="CC=gcc-arm-linux-gnueabi"
    - stage: arm
      os: linux
      dist: xenial
      compiler: gcc
      install:
        - sudo dpkg --add-architecture i386
        - sudo apt-get update
        - sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1
        - sudo apt-get install gcc-arm-linux-gnueabihf
      env: TARGET="--target arm-linux-gnueabi" CFLAGS="-march=armv7" CC="CC=gcc-arm-linux-gnueabi" LDFLAGS="-static"

    # MIPS architecture build
    - stage: mips
      os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - u-boot-tools
      install: sudo apt-get install gcc-mips-linux-gnu

    # PowerPC architecture build
    - stage: powerpc
      os: linux
      dist: xenial
      compiler: gcc
      install: sudo apt-get install gcc-powerpc-linux-gnu

    # OSX build with clang
    - stage: osx
      os: osx
      compiler: clang

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - cd src
  - ./configure $BUILD $HOST $TARGET
  - make $CC
  - file boa
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then objdump -f boa; fi
  - stat boa
  - sha512sum boa