sudo: enabled
language: c

branches:
  only:
  - master

# Follow DynamoRIO's lead and use a jobs approach over os, compiler, env matrix
jobs:
  include:
    # Linux build default with gcc
    - os: linux
      compiler: gcc
    # Linux build default with clang
    - os: linux
      compiler: clang
    # OSX build default with gcc
    - os: osx
      compiler: clang
    # OSX build default with clang
    - os: osx
      compiler: clang


install:
  - sudo apt-get install bison flex

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - cd src
  - ./configure
  - make