sudo: enabled
language: c

branches:
  only:
  - master

os:
  - linux
  - osx

dist:
  - precise
  - trusty
  - xenial
  - bionic

compiler:
  - gcc
  - clang

# Do not error on failures in OSX, which is not the target system
matrix:
  allow_failures:
    - os: osx

install:
  - if [ "$APT_INSTALL_BISON_FLEX" = "true" ]; then sudo apt-get install bison flex; fi

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - cd src
  - ./configure
  - make