sudo: enabled
language: c

branches:
  only:
  - master

notifications:
  email:
    on_success: never

# Do not error on failures in OSX, which is not the target system
matrix:
  allow_failures:
    - os: osx

# Follow DynamoRIO's lead and use a jobs approach over os, compiler, env matrix
jobs:
  include:
    # Default Linux builds with gcc and clang
    - stage: Build_Default
      os: linux
      dist: xenial
      compiler: gcc
    - stage: Build_Default
      os: linux
      dist: xenial
      compiler: clang
    - stage: Build_Default
      os: linux
      dist: bionic
      compiler: gcc
    - stage: Build_Default
      os: linux
      dist: bionic
      compiler: clang
    # MIPS architecture build using Xenial
    - stage: MIPS
      os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - u-boot-tools
      script: sudo apt-get install gcc-mips-linux-gnu
    # PowerPC architecture build using Xenial
    - stage: PowerPC
      os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-powerpc-linux-gnu
    # Default OSX builds with gcc and clang
    - stage: Build_OSX
      os: osx
      compiler: gcc
    - stage: Build_OSX
      os: osx
      compiler: clang

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - cd src
  - ./configure
  - make