sudo: enabled
language: c

branches:
  only:
  - master

notifications:
  email:
    on_success: never

# Do not error on failures in OSX, which is not the target system
matrix:
  allow_failures:
    - os: osx

# Follow DynamoRIO's lead and use a jobs approach over os, compiler, env matrix
jobs:
  include:

    # Default Linux builds with gcc and clang
    - stage: default
      os: linux
      dist: xenial
      compiler: gcc
    - stage: default
      os: linux
      dist: xenial
      compiler: clang
    - stage: default
      os: linux
      dist: bionic
      compiler: gcc
    - stage: default
      os: linux
      dist: bionic
      compiler: clang

    # Static Linux builds with gcc and clang
    - stage: static
      os: linux
      dist: xenial
      compiler: gcc
      env: LDFLAGS="-static"
    - stage: static
      os: linux
      dist: xenial
      compiler: clang
      env: LDFLAGS="-static"
    - stage: static
      os: linux
      dist: bionic
      compiler: gcc
      env: LDFLAGS="-static"
    - stage: static
      os: linux
      dist: bionic
      compiler: clang
      env: LDFLAGS="-static"

    # MIPS architecture build using Xenial
    - stage: mips
      os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - u-boot-tools
      install: sudo apt-get install gcc-mips-linux-gnu

    # PowerPC architecture build using Xenial
    - stage: powerpc
      os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-powerpc-linux-gnu

    # Default OSX builds with gcc and clang
    - stage: osx
      os: osx
      compiler: gcc
    - stage: osx
      os: osx
      compiler: clang

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - cd src
  - ./configure --build x86_64-pc-linux-gnu LDFLAGS="$LDFLAGS"
  - make
  - file boa
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then objdump -f boa; fi
  - du -h .